### ISSUE TITLE
[Release One]Unablle to edit response value.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#81] opened 2019-07-10 07:55 UTC
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   10/07/2019   |  
| Detected in Release | One |  
| Severity |Medium |
| Priority |Medium |
| Module | Manage Response|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select a project and domain.
3. Navigate to response tab.
4. Click on response .
5. Try to modify response value.

**Expected Result:**Eva should allow user to modify response values.

**Actual Result:** Eva is not allowing user to change response values.

![image](https://user-images.githubusercontent.com/47655741/60951129-1c3eda80-a316-11e9-845d-89d0e45d39f4.png)

**Comment by nishant1712** [comment] 2019-11-05 09:41
Duplicate of #71, hence closing.

**Closed by nishant1712** 2019-11-05 09:41 UTC
Labels: Deferred, bug
